"""empty message

Revision ID: e699e965701b
Revises: b45bd03b034f
Create Date: 2019-11-18 15:17:17.343988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e699e965701b'
down_revision = 'b45bd03b034f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flag', sa.Column('user_id', sa.Integer(), nullable=False))
    op.alter_column('flag', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('flag', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('flag', 'user_id')
    # ### end Alembic commands ###
